fix: updated monitor version
dialectlabs/solana-monitoring-service pull request #4
Opened 2022-07-12 18:17 UTC by AlekseiPetrovDev

2022-07-12 18:42 UTC, tsmbl requested changes
Could you also please update deployment files

2022-07-12 18:42 UTC, tsmbl commented on src/monitoring.service.ts
> +      wallet: NodeDialectWalletAdapter.create(
please take a look at constructor of dialect sdk class, it can auto-load env var

2022-07-12 18:42 UTC, tsmbl commented on src/monitoring.service.ts
> +      environment: process.env.ENVIROMENT! as Environment,
How about RPC url?

2022-07-12 18:42 UTC, tsmbl commented on src/monitoring.service.ts
> +      subscribersCacheTTL: Duration.fromObject({ seconds: 5 }),
Let's have this number smaller e.g. 1 min or 5 min

2022-07-13 06:39 UTC, gklawcode commented on deployment/deployment-devnet.yaml
> +        - env:
was this indention intentional?

2022-07-13 06:43 UTC, AlekseiPetrovDev commented on deployment/deployment-devnet.yaml
> +        - env:
I think prettier made it

2022-07-13 06:51 UTC, gklawcode commented on package.json
>      "@dialectlabs/web3": "^0.2.0",
should use latest 0.3.1?

2022-07-13 08:34 UTC, gklawcode commented on deployment/deployment-mainnet.yaml
>            value: "mainnet"
talked with Tsymbal, NETWORK_NAME should be "mainnet-beta"

2022-07-18 18:56 UTC, merged